### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by kof8855** [resetsix/cursor_device_id#3]
![image](https://github.com/user-attachments/assets/343a189c-6ad5-445e-babf-652a10d6374f)

**Comment by resetsix** [comment]
PowerShell中日期格式字符串的语法问题导致。

代码已更新。

**Comment by Duducoco** [comment]
> PowerShell中日期格式字符串的语法问题导致。
> 
> 代码已更新。

好像还是不行
```
所在位置 C:\Users\1\Downloads\device_id_win.ps1:26 字符: 41
+     $backup_time = (Get-Date).ToString("yyyyMMddHHmmss")
+                                         ~~~~~~~~~~~~~~~~
表达式或语句中包含意外的标记“yyyyMMddHHmmss")
    Copy-Item $machine_id_path "$machine_id_path.backup_$backup_time" -ErrorAction Stop
    Copy-Item $storage_json_path "$storage_json_path.backup_$backup_time" -ErrorAction Stop
    Write-Log "宸插垱寤洪厤缃枃浠跺浠?”。
所在位置 C:\Users\1\Downloads\device_id_win.ps1:10 字符: 5
+ try {
+     ~
语句块或类型定义中缺少右“}”。
所在位置 C:\Users\1\Downloads\device_id_win.ps1:65 字符: 2
+ }
+  ~
Try 语句缺少自己的 Catch 或 Finally 块。
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken
```

**Comment by resetsix** [comment]
@Duducoco 已更新，可以再帮忙试一下吗

**Comment by Duducoco** [comment]
> @Duducoco 已更新，可以再帮忙试一下吗

```
(base) PS C:\Users\1\Downloads> Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process
(base) PS C:\Users\1\Downloads> .\device_id_win.ps1
所在位置 C:\Users\1\Downloads\device_id_win.ps1:26 字符: 33
+     Copy-Item $machine_id_path "$machine_id_path.backup_$backup_time" ...
+                                 ~~~~~~~~~~~~~~~~
表达式或语句中包含意外的标记“$machine_id_path”。
所在位置 C:\Users\1\Downloads\device_id_win.ps1:26 字符: 57
+ ... hine_id_path "$machine_id_path.backup_$backup_time" -ErrorAction Stop
+                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
表达式或语句中包含意外的标记“$backup_time" -ErrorAction Stop
    Copy-Item $storage_json_path "$storage_json_path.backup_$backup_time" -ErrorAction Stop
    Write-Log "宸插垱寤洪厤缃枃浠跺浠?”。
所在位置 C:\Users\1\Downloads\device_id_win.ps1:26 字符: 69
+ ... hine_id_path "$machine_id_path.backup_$backup_time" -ErrorAction Stop
+                                                       ~~~~~~~~~~~~~~~~~~~
表达式或语句中包含意外的标记“" -ErrorAction Stop
    Copy-Item $storage_json_path "”。
所在位置 C:\Users\1\Downloads\device_id_win.ps1:27 字符: 35
+     Copy-Item $storage_json_path "$storage_json_path.backup_$backup_t ...
+                                   ~~~~~~~~~~~~~~~~~~
表达式或语句中包含意外的标记“$storage_json_path”。
所在位置 C:\Users\1\Downloads\device_id_win.ps1:27 字符: 61
+ ... _json_path "$storage_json_path.backup_$backup_time" -ErrorAction Stop
+                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
表达式或语句中包含意外的标记“$backup_time" -ErrorAction Stop
    Write-Log "宸插垱寤洪厤缃枃浠跺浠?”。
所在位置 C:\Users\1\Downloads\device_id_win.ps1:27 字符: 73
+ ... _json_path "$storage_json_path.backup_$backup_time" -ErrorAction Stop
+                                                       ~~~~~~~~~~~~~~~~~~~
表达式或语句中包含意外的标记“" -ErrorAction Stop
    Write-Log "”。
所在位置 C:\Users\1\Downloads\device_id_win.ps1:28 字符: 16
+     Write-Log "宸插垱寤洪厤缃枃浠跺浠?
+                ~~~~~~~~~~~~~~
表达式或语句中包含意外的标记“宸插垱寤洪厤缃枃浠跺浠?”。
所在位置 C:\Users\1\Downloads\device_id_win.ps1:10 字符: 5
+ try {
+     ~
语句块或类型定义中缺少右“}”。
所在位置 C:\Users\1\Downloads\device_id_win.ps1:64 字符: 2
+ }
+  ~
Try 语句缺少自己的 Catch 或 Finally 块。
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken
```

**Comment by resetsix** [comment]
> 
> ```
> (base) PS C:\Users\1\Downloads> Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process
> (base) PS C:\Users\1\Downloads> .\device_id_win.ps1
> 所在位置 C:\Users\1\Downloads\device_id_win.ps1:26 字符: 33
> +     Copy-Item $machine_id_path "$machine_id_path.backup_$backup_time" ...
> +                                 ~~~~~~~~~~~~~~~~
> 表达式或语句中包含意外的标记“$machine_id_path”。
> 所在位置 C:\Users\1\Downloads\device_id_win.ps1:26 字符: 57
> + ... hine_id_path "$machine_id_path.backup_$backup_time" -ErrorAction Stop
> +                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 表达式或语句中包含意外的标记“$backup_time" -ErrorAction Stop
>     Copy-Item $storage_json_path "$storage_json_path.backup_$backup_time" -ErrorAction Stop
>     Write-Log "宸插垱寤洪厤缃枃浠跺浠?”。
> 所在位置 C:\Users\1\Downloads\device_id_win.ps1:26 字符: 69
> + ... hine_id_path "$machine_id_path.backup_$backup_time" -ErrorAction Stop
> +                                                       ~~~~~~~~~~~~~~~~~~~
> 表达式或语句中包含意外的标记“" -ErrorAction Stop
>     Copy-Item $storage_json_path "”。
> 所在位置 C:\Users\1\Downloads\device_id_win.ps1:27 字符: 35
> +     Copy-Item $storage_json_path "$storage_json_path.backup_$backup_t ...
> +                                   ~~~~~~~~~~~~~~~~~~
> 表达式或语句中包含意外的标记“$storage_json_path”。
> 所在位置 C:\Users\1\Downloads\device_id_win.ps1:27 字符: 61
> + ... _json_path "$storage_json_path.backup_$backup_time" -ErrorAction Stop
> +                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 表达式或语句中包含意外的标记“$backup_time" -ErrorAction Stop
>     Write-Log "宸插垱寤洪厤缃枃浠跺浠?”。
> 所在位置 C:\Users\1\Downloads\device_id_win.ps1:27 字符: 73
> + ... _json_path "$storage_json_path.backup_$backup_time" -ErrorAction Stop
> +                                                       ~~~~~~~~~~~~~~~~~~~
> 表达式或语句中包含意外的标记“" -ErrorAction Stop
>     Write-Log "”。
> 所在位置 C:\Users\1\Downloads\device_id_win.ps1:28 字符: 16
> +     Write-Log "宸插垱寤洪厤缃枃浠跺浠?
> +                ~~~~~~~~~~~~~~
> 表达式或语句中包含意外的标记“宸插垱寤洪厤缃枃浠跺浠?”。
> 所在位置 C:\Users\1\Downloads\device_id_win.ps1:10 字符: 5
> + try {
> +     ~
> 语句块或类型定义中缺少右“}”。
> 所在位置 C:\Users\1\Downloads\device_id_win.ps1:64 字符: 2
> + }
> +  ~
> Try 语句缺少自己的 Catch 或 Finally 块。
>     + CategoryInfo          : ParserError: (:) [], ParseException
>     + FullyQualifiedErrorId : UnexpectedToken
> ```

明白了，我晚上再改一下。感谢
